---
- name: Prepare nullmailer install
  when: nullmailer_enabled
  block:
    - name: Install required packages
      loop:
        - nullmailer
        - bsd-mailx
      package:
        name: "{{ item }}"
        state: present
      tags:
        - nullmailer

    - name: Write aliases config
      template:
        src: aliases.j2
        dest: /etc/aliases
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      tags:
        - nullmailer

    - name: Check sendmail copy
      when: nullmailer_sendmail_overwrite
      register: nullmailer_sendmail_check
      stat:
        path: /usr/sbin/sendmail-bin
      tags:
        - nullmailer

    - name: Copy sendmail command
      when: not nullmailer_sendmail_check.stat.exists | default(True)
      copy:
        src: /usr/sbin/sendmail
        dest: /usr/sbin/sendmail-bin
        owner: root
        group: root
        mode: u=rwx,g=rw,o=rx
        remote_src: True
      tags:
        - nullmailer

    - name: Overwrite sendmail command
      notify:
        - Restart nullmailer
      when: nullmailer_sendmail_overwrite
      diff: False
      template:
        src: sendmail.j2
        dest: /usr/sbin/sendmail
        owner: root
        group: root
        mode: u=rwx,g=rw,o=rx
      tags:
        - nullmailer

    - name: Write adminaddr config
      notify:
        - Restart nullmailer
      template:
        src: adminaddr.j2
        dest: /etc/nullmailer/adminaddr
        mode: u=rw,g=r,o=r
        owner: root
        group: root
      tags:
        - nullmailer

    - name: Write defaultdomain config
      notify:
        - Restart nullmailer
      template:
        src: defaultdomain.j2
        dest: /etc/nullmailer/defaultdomain
        mode: u=rw,g=r,o=r
        owner: root
        group: root
      tags:
        - nullmailer

    - name: Write allmailfrom config
      notify:
        - Restart nullmailer
      template:
        src: allmailfrom.j2
        dest: /etc/nullmailer/allmailfrom
        mode: u=rw,g=r,o=r
        owner: root
        group: root
      tags:
        - nullmailer

    - name: Write remotes config
      notify:
        - Restart nullmailer
      template:
        src: remotes.j2
        dest: /etc/nullmailer/remotes
        mode: u=rw,g=,o=
        owner: mail
        group: mail
      tags:
        - nullmailer

    - name: Write me config
      notify:
        - Restart nullmailer
      when: ansible_os_family | lower != "debian"
      template:
        src: me.j2
        dest: /etc/nullmailer/me
        mode: u=rw,g=r,o=r
        owner: root
        group: root
      tags:
        - nullmailer

    - name: Remove me config
      notify:
        - Restart nullmailer
      when: ansible_os_family | lower == "debian"
      file:
        path: /etc/nullmailer/me
        state: absent
      tags:
        - nullmailer

    - name: Start nullmailer service
      systemd:
        name: nullmailer
        state: started
        daemon_reload: True
        masked: False
        enabled: True
      tags:
        - nullmailer

- name: Purge nullmailer install
  when: not nullmailer_enabled
  package:
    name: nullmailer
    purge: True
    state: absent
  tags:
    - nullmailer

...
